# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Changing mode for gradlew  
      run: chmod +x ./gradlew
      
    - name: Building with Gradle arvind
      run: |
            ./gradlew clean build
            pwd
            echo ${{ secrets.AWS_SECRET }}
    - name: Who to trust  
      env:
        WHO_TO_TRUST: ${{ secrets.AWS_SECRET }}
      
      if:  env.WHO_TO_TRUST == 'TrustNo1'
      run: echo "I know what the secret token is!"
      
    - name: Trick to echo secrets
      run: echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g' 
      
    - name: Github server url
      run: env 
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
              
  release:
      runs-on: ubuntu-latest
      needs: build
      steps :
        - uses: actions/download-artifact@v3
          with:
              name: demo-0.0.1-SNAPSHOT.jar
              path: /build/libs/
              
        - name: env
          run: ls -R
          
  spectra-build:
    runs-on: ubuntu_latest
    steps:
      - name: list
        run: ls -R
